backend:
  name: git-gateway
  branch: master
media_folder: "public/images/uploads"
public_folder: ""
site_url: "https://noblecutsmeat.com"
logo_url: "https://noblecutsmeat.com/images/og-image.png"
locale: "en"
show_preview_links: true
collections:
  - name: "product"
    label: "Product"
    description: "Add and edit products."
    identifier_field: name
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Description", name: "body", widget: "markdown" }
