backend:
  name: git-gateway
  branch: master
media_folder: "public/images/uploads"
public_folder: ""
site_url: "https://noblecutsmeat.com"
logo_url: "https://noblecutsmeat.com/images/og-image.png"
locale: "en"
show_preview_links: true
collections:
  - name: "post"
    label: "Post"
    description: "Add and edit product entries."
    identifier_field: name
    folder: "products"
    create: true
    slug: "{{slug}}"
    preview: false
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
