backend:
  name: git-gateway
  branch: master
media_folder: "public/images/uploads"
public_folder: ""
site_url: "https://noblecutsmeat.com"
logo_url: "https://noblecutsmeat.com/images/og-image.png"
locale: en
show_preview_links: true
collections:
  - name: product
    label: Products
    description: "Add and edit products."
    identifier_field: name
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    preview: false
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Featured Image, name: thumbnail, widget: image }
      - {
          label: Price,
          name: price,
          widget: number,
          default: 500.00,
          value_type: float,
          step: 50,
        }
      - { label: Description, name: description, widget: text }
  - label: Pages
    name: pages
    files:
      - label: Home Page
        name: home
        file: "content/pages/home.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: text }
          - label: Blocks
            name: blocks
            widget: list
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Blurb, name: blurb, widget: text }
              - { label: Photo, name: photo, widget: image }
      - label: About Page
        name: about
        file: "content/pages/about.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: text }
          - { label: Photo, name: photo, widget: image }
          - { lable: Outro, name: outro, widget: text }
          - label: FAQs
            name: faqs
            widget: list
            fields:
              - { label: Question, name: question, widget: string }
              - { label: Answer, name: answer, widget: text }
